---
- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip

- name: Install Pip packages
  pip: name={{ item }}
  with_items:
    - influxdb

- apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- apt_repository:
    repo: deb https://repos.influxdata.com/debian stretch stable
    state: present

- name: Install influxdb
  apt: name='influxdb' state='present' update_cache='yes'

- name: Install influxdb config file
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: influxdb
    group: influxdb
    mode: "u=rw,g=r,o=r"
  notify: Restart influxdb

- name: Ensure influxdb is running and enabled.
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Create influx admin user
  command: "influx -username {{ influxdb_username }} -password {{ influxdb_password }} -execute \"CREATE USER {{ influxdb_username }} WITH PASSWORD '{{ influxdb_password }}' WITH ALL PRIVILEGES\""

- name: Create databases
  influxdb_database:
    username: "{{ influxdb_username }}"
    password: "{{ influxdb_password }}"
    hostname: localhost
    database_name: "{{ item.name }}"
    state: present
  with_items: "{{ influxdb_databases }}"

- name: Set retention on databases
  influxdb_retention_policy:
    username: "{{ influxdb_username }}"
    password: "{{ influxdb_password }}"
    database_name: "{{ item.name }}"
    policy_name: default
    default: true
    duration: "{{ item.duration }}"
    replication: 1
  with_items: "{{ influxdb_databases }}"

- name: Create influx users
  command: "influx -username {{ influxdb_username }} -password {{ influxdb_password }} -execute \"CREATE USER {{ item.username }} WITH PASSWORD '{{ item.password }}'\""
  with_items: "{{ influxdb_users }}"

- name: Create user grants
  command: "influx -username {{ influxdb_username }} -password {{ influxdb_password }} -execute \"GRANT {{ item.permission }} ON {{ item.database }} TO {{ item.username }}\""
  with_items: "{{ influxdb_grants }}"

