---
- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: Reload nginx to activate letsencrypt site
  service: name=nginx state=restarted

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload

- name: Add nginx https site
  template:
    src: "nginx-01_https.conf"
    dest: "/etc/nginx/sites-available/01_https.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart nginx

- file:
    src: "/etc/nginx/sites-available/01_https.conf"
    dest: "/etc/nginx/sites-enabled/01_https.conf"
    state: link
