---
- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - nginx
    - letsencrypt

- name: Add nginx gzip config
  template:
    src: "nginx-gzip.conf"
    dest: "/etc/nginx/conf.d/gzip.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart nginx

- name: Add nginx iot site
  template:
    src: "nginx-00_iot.conf"
    dest: "/etc/nginx/sites-available/00_iot.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart nginx

- file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- file:
    src: "/etc/nginx/sites-available/00_iot.conf"
    dest: "/etc/nginx/sites-enabled/00_iot.conf"
    state: link

- import_tasks: letsencrypt.yml
  tags: [ 'letsencrypt' ]
  when: letsencrypt_email is defined
