---
- name: Install required Python modules
  apt: pkg={{ item }} state=present
  with_items:
    - python3
    - python3-venv
    - python3-pip

- name: Create homeassistant group
  group:
    name: homeassistant
    state: present

- name: Create homeassistant user
  user:
    name: homeassistant
    group: homeassistant
    groups: homeassistant
    state: present
    shell: "/bin/bash"
    system: yes
    createhome: yes
  register: hass_user_created

- name: Create homeassistant dir
  file:
    path: /srv/homeassistant
    state: directory
    mode: 0755
    owner: homeassistant
    group: homeassistant

- name: Create homeassistant config dir
  file:
    path: /home/homeassistant/.homeassistant
    state: directory
    mode: 0755
    owner: homeassistant
    group: homeassistant

- script: ../scripts/hass-setup.sh
  become_user: homeassistant
  when: hass_user_created.changed

- name: Install systemd unit file
  template:
    src: homeassistant.service.j2
    dest: /etc/systemd/system/homeassistant.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart homeassistant

- name: Ensure homeassistant is running and enabled.
  service:
    name: homeassistant
    state: started
    enabled: yes

- name: Add homeassistant configuration files
  template:
    src: "{{ item }}"
    dest: /home/homeassistant/.homeassistant/{{ item | basename }}
    owner: homeassistant
    group: homeassistant
    mode: "u=rw,g=r,o="
  notify: Restart homeassistant
  with_fileglob:
    - "{{ hass_config_glob }}"
  when: hass_config_glob is defined
