---
- name: Install mosquitto
  apt: pkg=mosquitto state=present

- name: Create mosquitto passwd file
  copy:
    content: ""
    dest: "{{ mosquitto_passwd_file }}"
    force: no
    owner: mosquitto
    group: mosquitto
    mode: "u=rw,g=r,o="
  register: mosquitto_pass_file

- name: Add mosquitto user
  command: mosquitto_passwd -b {{ mosquitto_passwd_file }} {{ mosquitto_username }} {{ mosquitto_password }}
  when: mosquitto_pass_file.changed

- name: Copy mosquitto config
  template:
    src: mosquitto.conf.j2
    dest: "/etc/mosquitto/conf.d/mosquitto.conf"
    owner: mosquitto
    group: mosquitto
    mode: "u=rw,g=r,o="

- name: Ensure mosquitto is running and enabled.
  service:
    name: mosquitto
    state: started
    enabled: yes
