---
- hosts: "{{ variable_host | default('iot') }}"
  remote_user: pi
  become: true
  gather_facts: yes
  vars:
    hostname: "{{ ansible_hostname }}"
    development: false

  vars_files:
     - ../vars/iot.yml

  roles:
    - role: ../roles/bootstrap
      tags: [ 'bootstrap' ]

    - role: ../roles/hass
      tags: [ 'hass' ]

    - role: ../roles/node-red
      tags: [ 'node-red' ]

    - role: ../roles/mosquitto
      tags: [ 'mosquitto' ]

    - role: ../roles/influxdb
      tags: [ 'influxdb' ]

    - role: ../roles/grafana
      tags: [ 'grafana' ]

    - role: ../roles/iot-nginx
      tags: [ 'nginx' ]

    - role: ../roles/dnspark
      tags: [ 'dnspark' ]

    - role: dj-wasabi.telegraf
      telegraf_agent_version: 1.5.3
      telegraf_agent_interval: 30
      telegraf_agent_round_interval: true
      telegraf_agent_flush_interval: 70
      telegraf_agent_flush_jitter: 15
      telegraf_agent_hostname: ""
      telegraf_agent_output:
        - type: influxdb
          config:
            - urls = ["http://localhost:8086"]
            - database = "telegraf"
            - username = "{{ telegraf_username }}"
            - password = "{{ telegraf_password }}"
      telegraf_plugins_default:
        - plugin: nginx
          config:
            - urls = ["http://127.0.0.1/stats"]
        - plugin: cpu
          config:
            - totalcpu = true
        - plugin: disk
        - plugin: io
        - plugin: mem
        - plugin: system
        - plugin: swap
        - plugin: net
        - plugin: processes
      tags: [ 'telegraf' ]

    - role: franklinkim.ufw
      ufw_rules:
        - port: 22
          rule: allow
        - port: 80
          rule: allow
        - port: 443
          rule: allow
        - port: 8086
          from_ip: "{{ local_cidr }}"
      tags: [ 'ufw' ]
